# -*- coding: utf-8 -*-
"""Colab Shell.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XKowB0s5b60OcaYOuS5GRTIiiPF2mcQo
"""

!pip install google_colab_shell
from google_colab_shell import getshell

getshell()